// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/srvhistoryuserlogin/proto/srvhistoryuserlogin.proto

package SrvHistoryUserLogin

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/idoall/MicroService-UserPowerManager/srv/srvusers/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddRequest struct {
	User                 *proto1.User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	GeoRemoteAddr        string       `protobuf:"bytes,2,opt,name=GeoRemoteAddr,proto3" json:"GeoRemoteAddr,omitempty"`
	GeoCountry           string       `protobuf:"bytes,3,opt,name=GeoCountry,proto3" json:"GeoCountry,omitempty"`
	GeoCity              string       `protobuf:"bytes,4,opt,name=GeoCity,proto3" json:"GeoCity,omitempty"`
	DeviceDetector       string       `protobuf:"bytes,5,opt,name=DeviceDetector,proto3" json:"DeviceDetector,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddeac33363d8b94, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetUser() *proto1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddRequest) GetGeoRemoteAddr() string {
	if m != nil {
		return m.GeoRemoteAddr
	}
	return ""
}

func (m *AddRequest) GetGeoCountry() string {
	if m != nil {
		return m.GeoCountry
	}
	return ""
}

func (m *AddRequest) GetGeoCity() string {
	if m != nil {
		return m.GeoCity
	}
	return ""
}

func (m *AddRequest) GetDeviceDetector() string {
	if m != nil {
		return m.DeviceDetector
	}
	return ""
}

type AddResponse struct {
	NewId                int64    `protobuf:"varint,1,opt,name=NewId,proto3" json:"NewId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bddeac33363d8b94, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetNewId() int64 {
	if m != nil {
		return m.NewId
	}
	return 0
}

func init() {
	proto.RegisterType((*AddRequest)(nil), "SrvHistoryUserLogin.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "SrvHistoryUserLogin.AddResponse")
}

func init() {
	proto.RegisterFile("srv/srvhistoryuserlogin/proto/srvhistoryuserlogin.proto", fileDescriptor_bddeac33363d8b94)
}

var fileDescriptor_bddeac33363d8b94 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0xfd, 0x03, 0x1a, 0x87, 0xc8, 0x61, 0xf5, 0xb0, 0xe1, 0xa0, 0xa4, 0x1a, 0xc3,
	0xc5, 0x36, 0xc1, 0x83, 0x67, 0x22, 0x09, 0x6a, 0xc4, 0x68, 0x09, 0x1f, 0xa0, 0x74, 0x27, 0xb0,
	0x09, 0x74, 0x70, 0x76, 0x5b, 0xc2, 0x37, 0xf3, 0xe3, 0x99, 0xdd, 0x6a, 0x50, 0x53, 0x2f, 0x9b,
	0xbc, 0xf9, 0xbd, 0xcc, 0x9b, 0x7d, 0x70, 0x6b, 0xb8, 0x8c, 0x0d, 0x97, 0x4b, 0x6d, 0x2c, 0xf1,
	0xae, 0x30, 0xc8, 0x2b, 0x5a, 0xe8, 0x3c, 0xde, 0x30, 0x59, 0xaa, 0x23, 0x91, 0x27, 0xe2, 0x64,
	0xca, 0xe5, 0x7d, 0x85, 0x66, 0x06, 0xf9, 0xc9, 0xa1, 0xee, 0xeb, 0x42, 0xdb, 0x65, 0x31, 0x8f,
	0x32, 0x5a, 0xc7, 0x5a, 0x51, 0xba, 0x5a, 0xc5, 0x13, 0x9d, 0x31, 0x4d, 0x91, 0x4b, 0x9d, 0xe1,
	0xb5, 0x73, 0xbe, 0xd0, 0x16, 0x79, 0x92, 0xe6, 0xe9, 0x02, 0x39, 0xfe, 0x4c, 0x77, 0xcb, 0xcd,
	0x3e, 0xd2, 0xcb, 0x2a, 0x27, 0x7c, 0x0f, 0x00, 0x86, 0x4a, 0x25, 0xf8, 0x56, 0xa0, 0xb1, 0x22,
	0x84, 0xa6, 0x5b, 0x22, 0x83, 0x5e, 0xd0, 0x6f, 0x0f, 0x3a, 0xd1, 0x94, 0xcb, 0x99, 0x77, 0xbb,
	0x37, 0xf1, 0x4c, 0x5c, 0xc2, 0xf1, 0x18, 0x29, 0xc1, 0x35, 0x59, 0x1c, 0x2a, 0xc5, 0xf2, 0x7f,
	0x2f, 0xe8, 0x1f, 0x25, 0x3f, 0x87, 0xe2, 0x0c, 0x60, 0x8c, 0x74, 0x47, 0x45, 0x6e, 0x79, 0x27,
	0x1b, 0xde, 0xf2, 0x6d, 0x22, 0x24, 0x1c, 0x3a, 0xa5, 0xed, 0x4e, 0x36, 0x3d, 0xfc, 0x92, 0xe2,
	0x0a, 0x3a, 0x23, 0x74, 0xff, 0x19, 0xa1, 0xc5, 0xcc, 0x12, 0xcb, 0x96, 0x37, 0xfc, 0x9a, 0x86,
	0x17, 0xd0, 0xf6, 0x97, 0x9b, 0x0d, 0xe5, 0x06, 0xc5, 0x29, 0xb4, 0x9e, 0x71, 0xfb, 0xa0, 0xfc,
	0xed, 0x8d, 0xa4, 0x12, 0x83, 0x14, 0xea, 0x9a, 0x14, 0x8f, 0xd0, 0x18, 0x2a, 0x25, 0xce, 0xa3,
	0x1a, 0x18, 0xed, 0xfb, 0xe8, 0xf6, 0xfe, 0x36, 0x54, 0xb1, 0xe1, 0xbf, 0xf9, 0x81, 0x6f, 0xf2,
	0xe6, 0x23, 0x00, 0x00, 0xff, 0xff, 0x61, 0x44, 0xd7, 0x8b, 0xec, 0x01, 0x00, 0x00,
}
