version: '3.6'
# https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-file-v2.md
services:
  consul:
    command: -server -bootstrap -rejoin 
    image: progrium/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  ##############################
  # jaeger
  ##############################
  jaeger:
    image: jaegertracing/all-in-one:1.11
    links:
      - consul
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
  ##############################
  # swagger
  ##############################
  swagger:
    build: ./swagger
    ports:
      - "18081:8080"