// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/srvusers/proto/srvusers.proto

// import public "google/protobuf/timestamp.proto";

package SrvUsers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	RealyName            string   `protobuf:"bytes,3,opt,name=RealyName,proto3" json:"RealyName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	AuthKey              string   `protobuf:"bytes,5,opt,name=AuthKey,proto3" json:"AuthKey,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	IsDel                bool     `protobuf:"varint,7,opt,name=IsDel,proto3" json:"IsDel,omitempty"`
	Note                 string   `protobuf:"bytes,8,opt,name=Note,proto3" json:"Note,omitempty"`
	ParentId             int64    `protobuf:"varint,9,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	LastUpdateTime       int64    `protobuf:"varint,11,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetRealyName() string {
	if m != nil {
		return m.RealyName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

func (m *User) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *User) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

type AddRequest struct {
	Models               *User    `protobuf:"bytes,1,opt,name=Models,proto3" json:"Models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetModels() *User {
	if m != nil {
		return m.Models
	}
	return nil
}

type AddResponse struct {
	NewUserId            int64    `protobuf:"varint,1,opt,name=NewUserId,proto3" json:"NewUserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetNewUserId() int64 {
	if m != nil {
		return m.NewUserId
	}
	return 0
}

type GetListRequest struct {
	PageSize             int64    `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	CurrentPageIndex     int64    `protobuf:"varint,2,opt,name=CurrentPageIndex,proto3" json:"CurrentPageIndex,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{3}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetListRequest) GetCurrentPageIndex() int64 {
	if m != nil {
		return m.CurrentPageIndex
	}
	return 0
}

func (m *GetListRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type GetListResponse struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	List                 []*User  `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{4}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetListResponse) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

type GetUserRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{5}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetUserRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type GetUserResponse struct {
	Models               *User    `protobuf:"bytes,1,opt,name=Models,proto3" json:"Models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{6}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetModels() *User {
	if m != nil {
		return m.Models
	}
	return nil
}

type UpdateRequest struct {
	Models               *User    `protobuf:"bytes,1,opt,name=Models,proto3" json:"Models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetModels() *User {
	if m != nil {
		return m.Models
	}
	return nil
}

type UpdateResponse struct {
	// 是否更新成功
	Updated              int64    `protobuf:"varint,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	UserIdArray          []string `protobuf:"bytes,1,rep,name=UserIdArray,proto3" json:"UserIdArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUserIdArray() []string {
	if m != nil {
		return m.UserIdArray
	}
	return nil
}

type DeleteResponse struct {
	// 是否删除成功,批量删除不需要返回值
	Deleted              int64    `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0950ecdad2a38eb6, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "SrvUsers.User")
	proto.RegisterType((*AddRequest)(nil), "SrvUsers.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "SrvUsers.AddResponse")
	proto.RegisterType((*GetListRequest)(nil), "SrvUsers.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "SrvUsers.GetListResponse")
	proto.RegisterType((*GetUserRequest)(nil), "SrvUsers.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "SrvUsers.GetUserResponse")
	proto.RegisterType((*UpdateRequest)(nil), "SrvUsers.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "SrvUsers.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "SrvUsers.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "SrvUsers.DeleteResponse")
}

func init() { proto.RegisterFile("srv/srvusers/proto/srvusers.proto", fileDescriptor_0950ecdad2a38eb6) }

var fileDescriptor_0950ecdad2a38eb6 = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x6f, 0x6b, 0x13, 0x4f,
	0x10, 0x4e, 0xee, 0xd2, 0xfc, 0x99, 0xd0, 0xfc, 0x7e, 0x2c, 0x55, 0xd7, 0x20, 0xe5, 0xdc, 0x17,
	0x25, 0x54, 0x48, 0xb1, 0x16, 0xc4, 0x17, 0x82, 0xf9, 0x23, 0x12, 0xac, 0x51, 0xae, 0xcd, 0x07,
	0x38, 0xdd, 0xc1, 0x06, 0x2e, 0xb9, 0xb8, 0xbb, 0x49, 0x8d, 0x1f, 0xc9, 0x2f, 0xe2, 0xd7, 0x92,
	0x9d, 0xbd, 0x7f, 0x49, 0x8b, 0xe8, 0x9b, 0x70, 0xcf, 0x33, 0x33, 0xcf, 0xcc, 0x3c, 0x73, 0x39,
	0x78, 0xaa, 0xd5, 0xe6, 0x4c, 0xab, 0xcd, 0x5a, 0xa3, 0xd2, 0x67, 0x2b, 0x95, 0x98, 0x24, 0x87,
	0x7d, 0x82, 0xac, 0x79, 0xa5, 0x36, 0x33, 0x8b, 0xc5, 0x4f, 0x0f, 0x6a, 0xf6, 0x89, 0x75, 0xc0,
	0x9b, 0x48, 0x5e, 0x0d, 0xaa, 0x3d, 0x3f, 0xf4, 0x26, 0x92, 0x75, 0xa1, 0x69, 0xf9, 0x69, 0xb4,
	0x40, 0xee, 0x05, 0xd5, 0x5e, 0x2b, 0xcc, 0x31, 0x7b, 0x02, 0xad, 0x10, 0xa3, 0x78, 0x4b, 0x41,
	0x9f, 0x82, 0x05, 0x61, 0x2b, 0x3f, 0x45, 0x5a, 0xdf, 0x26, 0x4a, 0xf2, 0x9a, 0xab, 0xcc, 0x30,
	0xe3, 0xd0, 0x18, 0xac, 0xcd, 0xcd, 0x7b, 0xdc, 0xf2, 0x03, 0x0a, 0x65, 0x90, 0x1d, 0xc1, 0xc1,
	0xdb, 0x45, 0x34, 0x8f, 0x79, 0x9d, 0x78, 0x07, 0x2c, 0x3b, 0xd1, 0x63, 0x8c, 0x79, 0x23, 0xa8,
	0xf6, 0x9a, 0xa1, 0x03, 0x8c, 0x41, 0x6d, 0x9a, 0x18, 0xe4, 0x4d, 0x4a, 0xa5, 0x67, 0xd7, 0x55,
	0xe1, 0xd2, 0x4c, 0x24, 0x6f, 0xd1, 0x16, 0x39, 0x66, 0xc7, 0x00, 0x23, 0x85, 0x91, 0xc1, 0xeb,
	0xf9, 0x02, 0x39, 0x50, 0xb4, 0xc4, 0xb0, 0x13, 0xe8, 0x5c, 0x46, 0xda, 0xcc, 0x56, 0x32, 0xcb,
	0x69, 0x53, 0xce, 0x1e, 0x2b, 0x2e, 0x00, 0x06, 0x52, 0x86, 0xf8, 0x6d, 0x8d, 0xda, 0xb0, 0x13,
	0xa8, 0x7f, 0x48, 0x24, 0xc6, 0x9a, 0x5c, 0x6b, 0x9f, 0x77, 0xfa, 0x99, 0xab, 0x7d, 0xfb, 0x1b,
	0xa6, 0x51, 0xf1, 0x0c, 0xda, 0x54, 0xa5, 0x57, 0xc9, 0x52, 0x93, 0x79, 0x53, 0xbc, 0xb5, 0x19,
	0xb9, 0xdf, 0x05, 0x21, 0x14, 0x74, 0xde, 0xa1, 0xb9, 0x9c, 0x6b, 0x93, 0xb5, 0xa1, 0xc5, 0xbe,
	0xe2, 0xd5, 0xfc, 0x07, 0xa6, 0xe9, 0x39, 0x66, 0xa7, 0xf0, 0xff, 0x68, 0xad, 0xec, 0x96, 0x96,
	0x9a, 0x2c, 0x25, 0x7e, 0xa7, 0x63, 0xf9, 0xe1, 0x1d, 0xde, 0x5a, 0xff, 0x51, 0x49, 0x54, 0xc3,
	0x6d, 0x7a, 0xb2, 0x0c, 0x8a, 0x19, 0xfc, 0x97, 0xf7, 0x4c, 0x87, 0x3c, 0x06, 0xb8, 0x4e, 0x4c,
	0x14, 0x8f, 0x92, 0xf5, 0xd2, 0xa4, 0x6d, 0x4b, 0x0c, 0x13, 0x50, 0xb3, 0xf9, 0xdc, 0x0b, 0xfc,
	0x7b, 0x36, 0xa7, 0x98, 0x18, 0xd3, 0x2a, 0x44, 0xa4, 0xab, 0x3c, 0x84, 0xfa, 0xce, 0xde, 0x29,
	0xfa, 0xd3, 0xbb, 0x26, 0x5e, 0xd1, 0x70, 0x4e, 0x25, 0x1d, 0xee, 0x6f, 0x8d, 0x7f, 0x09, 0x87,
	0xee, 0x78, 0xff, 0x7a, 0xb1, 0x53, 0xe8, 0x64, 0x85, 0x69, 0x4b, 0x0e, 0x0d, 0xc7, 0x64, 0xa3,
	0x67, 0x50, 0x3c, 0x87, 0xc3, 0x31, 0xc6, 0x58, 0x34, 0x09, 0xa0, 0xed, 0xd6, 0x1a, 0x28, 0x15,
	0x6d, 0x79, 0x35, 0xf0, 0x7b, 0xad, 0xb0, 0x4c, 0x59, 0xf9, 0xac, 0xa4, 0x90, 0x77, 0x4c, 0x2e,
	0x9f, 0xc2, 0xf3, 0x5f, 0x1e, 0xe4, 0x7f, 0x56, 0x76, 0x01, 0xfe, 0x40, 0x4a, 0x76, 0x54, 0x8c,
	0x5d, 0xbc, 0x8e, 0xdd, 0x07, 0x7b, 0xac, 0x93, 0x16, 0x15, 0xf6, 0x06, 0x1a, 0xe9, 0x79, 0x19,
	0x2f, 0x72, 0x76, 0xdf, 0xb2, 0xee, 0xe3, 0x7b, 0x22, 0x7b, 0x0a, 0xf4, 0x99, 0xd8, 0x55, 0x28,
	0x1d, 0x77, 0x4f, 0xa1, 0x7c, 0x30, 0x51, 0x61, 0xaf, 0xa1, 0xee, 0x0c, 0x63, 0x8f, 0x4a, 0x9e,
	0x97, 0x8f, 0xd3, 0xe5, 0x77, 0x03, 0x79, 0xf9, 0x10, 0xda, 0xc3, 0xc8, 0x7c, 0xb9, 0x71, 0xae,
	0x94, 0x35, 0x76, 0xbc, 0x2f, 0x6b, 0xec, 0x3a, 0x2c, 0x2a, 0x9f, 0xeb, 0xf4, 0xe9, 0x7b, 0xf1,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x53, 0xeb, 0x74, 0xcc, 0x1f, 0x05, 0x00, 0x00,
}
