// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/role/v1/proto/proto.proto

// import public "google/protobuf/timestamp.proto";

package SrvRole

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ForUserRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForUserRequest) Reset()         { *m = ForUserRequest{} }
func (m *ForUserRequest) String() string { return proto.CompactTextString(m) }
func (*ForUserRequest) ProtoMessage()    {}
func (*ForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{1}
}

func (m *ForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForUserRequest.Unmarshal(m, b)
}
func (m *ForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForUserRequest.Marshal(b, m, deterministic)
}
func (m *ForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForUserRequest.Merge(m, src)
}
func (m *ForUserRequest) XXX_Size() int {
	return xxx_messageInfo_ForUserRequest.Size(m)
}
func (m *ForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForUserRequest proto.InternalMessageInfo

func (m *ForUserRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type GetPermissionsForUserResponse struct {
	One                  []*TwoString `protobuf:"bytes,1,rep,name=One,proto3" json:"One,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetPermissionsForUserResponse) Reset()         { *m = GetPermissionsForUserResponse{} }
func (m *GetPermissionsForUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetPermissionsForUserResponse) ProtoMessage()    {}
func (*GetPermissionsForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{2}
}

func (m *GetPermissionsForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPermissionsForUserResponse.Unmarshal(m, b)
}
func (m *GetPermissionsForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPermissionsForUserResponse.Marshal(b, m, deterministic)
}
func (m *GetPermissionsForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPermissionsForUserResponse.Merge(m, src)
}
func (m *GetPermissionsForUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetPermissionsForUserResponse.Size(m)
}
func (m *GetPermissionsForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPermissionsForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPermissionsForUserResponse proto.InternalMessageInfo

func (m *GetPermissionsForUserResponse) GetOne() []*TwoString {
	if m != nil {
		return m.One
	}
	return nil
}

type TwoString struct {
	Two                  []string `protobuf:"bytes,1,rep,name=Two,proto3" json:"Two,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoString) Reset()         { *m = TwoString{} }
func (m *TwoString) String() string { return proto.CompactTextString(m) }
func (*TwoString) ProtoMessage()    {}
func (*TwoString) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{3}
}

func (m *TwoString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoString.Unmarshal(m, b)
}
func (m *TwoString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoString.Marshal(b, m, deterministic)
}
func (m *TwoString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoString.Merge(m, src)
}
func (m *TwoString) XXX_Size() int {
	return xxx_messageInfo_TwoString.Size(m)
}
func (m *TwoString) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoString.DiscardUnknown(m)
}

var xxx_messageInfo_TwoString proto.InternalMessageInfo

func (m *TwoString) GetTwo() []string {
	if m != nil {
		return m.Two
	}
	return nil
}

type DeletePermissionsForUserResponse struct {
	IsDel                bool     `protobuf:"varint,1,opt,name=IsDel,proto3" json:"IsDel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePermissionsForUserResponse) Reset()         { *m = DeletePermissionsForUserResponse{} }
func (m *DeletePermissionsForUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePermissionsForUserResponse) ProtoMessage()    {}
func (*DeletePermissionsForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{4}
}

func (m *DeletePermissionsForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePermissionsForUserResponse.Unmarshal(m, b)
}
func (m *DeletePermissionsForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePermissionsForUserResponse.Marshal(b, m, deterministic)
}
func (m *DeletePermissionsForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePermissionsForUserResponse.Merge(m, src)
}
func (m *DeletePermissionsForUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePermissionsForUserResponse.Size(m)
}
func (m *DeletePermissionsForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePermissionsForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePermissionsForUserResponse proto.InternalMessageInfo

func (m *DeletePermissionsForUserResponse) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

type RemoveFilteredPolicyRequest struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFilteredPolicyRequest) Reset()         { *m = RemoveFilteredPolicyRequest{} }
func (m *RemoveFilteredPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFilteredPolicyRequest) ProtoMessage()    {}
func (*RemoveFilteredPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{5}
}

func (m *RemoveFilteredPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFilteredPolicyRequest.Unmarshal(m, b)
}
func (m *RemoveFilteredPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFilteredPolicyRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFilteredPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFilteredPolicyRequest.Merge(m, src)
}
func (m *RemoveFilteredPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFilteredPolicyRequest.Size(m)
}
func (m *RemoveFilteredPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFilteredPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFilteredPolicyRequest proto.InternalMessageInfo

func (m *RemoveFilteredPolicyRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type AddPolicyRequest struct {
	S1                   string   `protobuf:"bytes,1,opt,name=s1,proto3" json:"s1,omitempty"`
	S2                   string   `protobuf:"bytes,2,opt,name=s2,proto3" json:"s2,omitempty"`
	S3                   string   `protobuf:"bytes,3,opt,name=s3,proto3" json:"s3,omitempty"`
	S4                   string   `protobuf:"bytes,4,opt,name=s4,proto3" json:"s4,omitempty"`
	S5                   string   `protobuf:"bytes,5,opt,name=s5,proto3" json:"s5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPolicyRequest) Reset()         { *m = AddPolicyRequest{} }
func (m *AddPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*AddPolicyRequest) ProtoMessage()    {}
func (*AddPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{6}
}

func (m *AddPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPolicyRequest.Unmarshal(m, b)
}
func (m *AddPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPolicyRequest.Marshal(b, m, deterministic)
}
func (m *AddPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPolicyRequest.Merge(m, src)
}
func (m *AddPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_AddPolicyRequest.Size(m)
}
func (m *AddPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPolicyRequest proto.InternalMessageInfo

func (m *AddPolicyRequest) GetS1() string {
	if m != nil {
		return m.S1
	}
	return ""
}

func (m *AddPolicyRequest) GetS2() string {
	if m != nil {
		return m.S2
	}
	return ""
}

func (m *AddPolicyRequest) GetS3() string {
	if m != nil {
		return m.S3
	}
	return ""
}

func (m *AddPolicyRequest) GetS4() string {
	if m != nil {
		return m.S4
	}
	return ""
}

func (m *AddPolicyRequest) GetS5() string {
	if m != nil {
		return m.S5
	}
	return ""
}

type GetRolesForUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesForUserRequest) Reset()         { *m = GetRolesForUserRequest{} }
func (m *GetRolesForUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetRolesForUserRequest) ProtoMessage()    {}
func (*GetRolesForUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{7}
}

func (m *GetRolesForUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesForUserRequest.Unmarshal(m, b)
}
func (m *GetRolesForUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesForUserRequest.Marshal(b, m, deterministic)
}
func (m *GetRolesForUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesForUserRequest.Merge(m, src)
}
func (m *GetRolesForUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetRolesForUserRequest.Size(m)
}
func (m *GetRolesForUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesForUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesForUserRequest proto.InternalMessageInfo

func (m *GetRolesForUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetRolesForUserResponse struct {
	Roles                []string `protobuf:"bytes,1,rep,name=Roles,proto3" json:"Roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRolesForUserResponse) Reset()         { *m = GetRolesForUserResponse{} }
func (m *GetRolesForUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetRolesForUserResponse) ProtoMessage()    {}
func (*GetRolesForUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{8}
}

func (m *GetRolesForUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRolesForUserResponse.Unmarshal(m, b)
}
func (m *GetRolesForUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRolesForUserResponse.Marshal(b, m, deterministic)
}
func (m *GetRolesForUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRolesForUserResponse.Merge(m, src)
}
func (m *GetRolesForUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetRolesForUserResponse.Size(m)
}
func (m *GetRolesForUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRolesForUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRolesForUserResponse proto.InternalMessageInfo

func (m *GetRolesForUserResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AddGroupingPolicyRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	UserGroup            []string `protobuf:"bytes,2,rep,name=UserGroup,proto3" json:"UserGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupingPolicyRequest) Reset()         { *m = AddGroupingPolicyRequest{} }
func (m *AddGroupingPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*AddGroupingPolicyRequest) ProtoMessage()    {}
func (*AddGroupingPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6b543611efdeddb8, []int{9}
}

func (m *AddGroupingPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupingPolicyRequest.Unmarshal(m, b)
}
func (m *AddGroupingPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupingPolicyRequest.Marshal(b, m, deterministic)
}
func (m *AddGroupingPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupingPolicyRequest.Merge(m, src)
}
func (m *AddGroupingPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_AddGroupingPolicyRequest.Size(m)
}
func (m *AddGroupingPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupingPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupingPolicyRequest proto.InternalMessageInfo

func (m *AddGroupingPolicyRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AddGroupingPolicyRequest) GetUserGroup() []string {
	if m != nil {
		return m.UserGroup
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "SrvRole.Empty")
	proto.RegisterType((*ForUserRequest)(nil), "SrvRole.ForUserRequest")
	proto.RegisterType((*GetPermissionsForUserResponse)(nil), "SrvRole.GetPermissionsForUserResponse")
	proto.RegisterType((*TwoString)(nil), "SrvRole.TwoString")
	proto.RegisterType((*DeletePermissionsForUserResponse)(nil), "SrvRole.DeletePermissionsForUserResponse")
	proto.RegisterType((*RemoveFilteredPolicyRequest)(nil), "SrvRole.RemoveFilteredPolicyRequest")
	proto.RegisterType((*AddPolicyRequest)(nil), "SrvRole.AddPolicyRequest")
	proto.RegisterType((*GetRolesForUserRequest)(nil), "SrvRole.GetRolesForUserRequest")
	proto.RegisterType((*GetRolesForUserResponse)(nil), "SrvRole.GetRolesForUserResponse")
	proto.RegisterType((*AddGroupingPolicyRequest)(nil), "SrvRole.AddGroupingPolicyRequest")
}

func init() { proto.RegisterFile("srv/role/v1/proto/proto.proto", fileDescriptor_6b543611efdeddb8) }

var fileDescriptor_6b543611efdeddb8 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0xcd, 0xa7, 0x75, 0xaf, 0x10, 0xeb, 0xa5, 0xda, 0x31, 0x1a, 0x8c, 0x43, 0x90, 0x0a, 0x92,
	0x90, 0xa4, 0x85, 0xbe, 0x49, 0xa1, 0x6d, 0x14, 0xa4, 0x96, 0x6d, 0xf5, 0xc1, 0x27, 0xad, 0xb9,
	0x94, 0x85, 0xdd, 0x9d, 0x75, 0x66, 0xba, 0xa5, 0xff, 0xcb, 0x1f, 0x28, 0x33, 0xbb, 0x9d, 0x26,
	0xfb, 0x11, 0x5f, 0x36, 0xf7, 0xcc, 0xfd, 0xd8, 0x39, 0xe7, 0x9e, 0x2c, 0x0c, 0x94, 0x4c, 0x27,
	0x52, 0x84, 0x34, 0x49, 0xa7, 0x93, 0x44, 0x0a, 0x2d, 0xb2, 0xe7, 0xd8, 0x3e, 0x71, 0xeb, 0x42,
	0xa6, 0xbe, 0x08, 0x89, 0x6f, 0x41, 0xf7, 0x24, 0x4a, 0xf4, 0x1d, 0x1f, 0x41, 0xef, 0x54, 0xc8,
	0x6f, 0x8a, 0xa4, 0x4f, 0x7f, 0x6e, 0x48, 0x69, 0x44, 0xe8, 0x18, 0xc8, 0x9a, 0xc3, 0xe6, 0x9e,
	0xe7, 0xdb, 0x98, 0x9f, 0xc0, 0x60, 0x41, 0xfa, 0x9c, 0x64, 0x14, 0x28, 0x15, 0x88, 0x58, 0xb9,
	0x1e, 0x95, 0x88, 0x58, 0x11, 0x8e, 0xa0, 0xfd, 0x35, 0x26, 0xd6, 0x1c, 0xb6, 0xf7, 0x9e, 0xcc,
	0x70, 0x9c, 0xbf, 0x66, 0x7c, 0x79, 0x2b, 0x2e, 0xb4, 0x0c, 0xe2, 0x6b, 0xdf, 0xa4, 0xf9, 0x00,
	0x3c, 0x77, 0x82, 0xdb, 0xd0, 0xbe, 0xbc, 0x15, 0xb6, 0xc5, 0xf3, 0x4d, 0xc8, 0x0f, 0x61, 0x78,
	0x4c, 0x21, 0x69, 0xda, 0xf0, 0xa2, 0x1d, 0xe8, 0x7e, 0x56, 0xc7, 0x14, 0xda, 0xeb, 0x3d, 0xf6,
	0x33, 0xc0, 0xa7, 0xf0, 0xca, 0xa7, 0x48, 0xa4, 0x74, 0x1a, 0x84, 0x9a, 0x24, 0x2d, 0xcf, 0x45,
	0x18, 0xfc, 0xbe, 0x5b, 0xa1, 0x64, 0x34, 0xb9, 0xa7, 0x64, 0x62, 0x7e, 0x05, 0xdb, 0x47, 0xcb,
	0x42, 0x5d, 0x0f, 0x5a, 0x6a, 0x9a, 0x57, 0xb5, 0xd4, 0xd4, 0xe2, 0x19, 0x6b, 0xe5, 0x78, 0x66,
	0xf1, 0x9c, 0xb5, 0x73, 0x3c, 0xb7, 0x78, 0x9f, 0x75, 0x72, 0xbc, 0x6f, 0xf1, 0x01, 0xeb, 0xe6,
	0xf8, 0x80, 0x7f, 0x80, 0x17, 0x0b, 0xd2, 0x46, 0x09, 0x55, 0x16, 0xf9, 0xec, 0x57, 0xe4, 0x6e,
	0x64, 0x62, 0x3e, 0x81, 0xdd, 0x52, 0xf5, 0x03, 0x6b, 0x7b, 0x9e, 0xab, 0x95, 0x01, 0xfe, 0x05,
	0xd8, 0xd1, 0x72, 0xb9, 0x90, 0xe2, 0x26, 0x09, 0xe2, 0xeb, 0x12, 0xe5, 0xe2, 0x16, 0xf1, 0x35,
	0x78, 0xe6, 0xd7, 0x36, 0xb0, 0x96, 0x9d, 0xf4, 0x70, 0x30, 0xfb, 0xdb, 0x81, 0x7b, 0x7b, 0xe0,
	0x0f, 0x78, 0x5e, 0xb9, 0x6f, 0xdc, 0x75, 0xab, 0x5d, 0x27, 0xd4, 0x7f, 0xe7, 0x12, 0x1b, 0x8d,
	0xc2, 0x1b, 0xf8, 0x13, 0x58, 0xdd, 0x96, 0xeb, 0xc7, 0xbf, 0x77, 0x89, 0xff, 0x39, 0x84, 0x37,
	0xf0, 0x0c, 0x76, 0xaa, 0xdc, 0x80, 0x23, 0x37, 0x64, 0x83, 0x59, 0xfa, 0x3d, 0x57, 0x95, 0xfd,
	0x43, 0x1a, 0x78, 0x08, 0x9e, 0xb3, 0x0a, 0xbe, 0x74, 0xe9, 0xa2, 0x7d, 0x2a, 0x3a, 0xbf, 0xc3,
	0xd3, 0xc2, 0x4a, 0xf1, 0xcd, 0xaa, 0x50, 0x15, 0xd6, 0xe8, 0x0f, 0xeb, 0x0b, 0x1c, 0xc3, 0x8f,
	0x80, 0x99, 0x0e, 0x6b, 0xa3, 0x6b, 0xd5, 0x2b, 0x5f, 0xec, 0x13, 0x3c, 0x2b, 0x59, 0x07, 0xdf,
	0xae, 0x52, 0xab, 0xb4, 0x55, 0x79, 0xd2, 0xd5, 0x23, 0xfb, 0x65, 0x99, 0xff, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x07, 0x95, 0x39, 0xb3, 0x7a, 0x04, 0x00, 0x00,
}
