// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/srvusersgroup/proto/srvusersgroup.proto

// import public "google/protobuf/timestamp.proto";

package SrvUsersGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UsersGroup struct {
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 用户组名称
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	// 所属组Id
	ParentID int64 `protobuf:"varint,3,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	// 排序
	Sorts int64 `protobuf:"varint,4,opt,name=Sorts,proto3" json:"Sorts,omitempty"`
	// 备注
	Note string `protobuf:"bytes,5,opt,name=Note,proto3" json:"Note,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,6,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	// 最后是错新时间
	LastUpdateTime       int64    `protobuf:"varint,7,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UsersGroup) Reset()         { *m = UsersGroup{} }
func (m *UsersGroup) String() string { return proto.CompactTextString(m) }
func (*UsersGroup) ProtoMessage()    {}
func (*UsersGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{0}
}

func (m *UsersGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersGroup.Unmarshal(m, b)
}
func (m *UsersGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersGroup.Marshal(b, m, deterministic)
}
func (m *UsersGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersGroup.Merge(m, src)
}
func (m *UsersGroup) XXX_Size() int {
	return xxx_messageInfo_UsersGroup.Size(m)
}
func (m *UsersGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersGroup.DiscardUnknown(m)
}

var xxx_messageInfo_UsersGroup proto.InternalMessageInfo

func (m *UsersGroup) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UsersGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UsersGroup) GetParentID() int64 {
	if m != nil {
		return m.ParentID
	}
	return 0
}

func (m *UsersGroup) GetSorts() int64 {
	if m != nil {
		return m.Sorts
	}
	return 0
}

func (m *UsersGroup) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *UsersGroup) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *UsersGroup) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

type AddRequest struct {
	Model                *UsersGroup `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetModel() *UsersGroup {
	if m != nil {
		return m.Model
	}
	return nil
}

type AddResponse struct {
	NewID                int64    `protobuf:"varint,1,opt,name=NewID,proto3" json:"NewID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetNewID() int64 {
	if m != nil {
		return m.NewID
	}
	return 0
}

type GetListRequest struct {
	PageSize             int64    `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	CurrentPageIndex     int64    `protobuf:"varint,2,opt,name=CurrentPageIndex,proto3" json:"CurrentPageIndex,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{3}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetListRequest) GetCurrentPageIndex() int64 {
	if m != nil {
		return m.CurrentPageIndex
	}
	return 0
}

func (m *GetListRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type GetListResponse struct {
	TotalCount           int64         `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	List                 []*UsersGroup `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{4}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetListResponse) GetList() []*UsersGroup {
	if m != nil {
		return m.List
	}
	return nil
}

type GetRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetResponse struct {
	Model                *UsersGroup `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetModel() *UsersGroup {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateRequest struct {
	Model                *UsersGroup `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetModel() *UsersGroup {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateResponse struct {
	// 是否更新成功
	Updated              int64    `protobuf:"varint,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	IdArray              []string `protobuf:"bytes,1,rep,name=IdArray,proto3" json:"IdArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetIdArray() []string {
	if m != nil {
		return m.IdArray
	}
	return nil
}

type DeleteResponse struct {
	// 是否删除成功,批量删除不需要返回值
	Deleted              int64    `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2ef7a1dd69266781, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*UsersGroup)(nil), "SrvUsersGroup.UsersGroup")
	proto.RegisterType((*AddRequest)(nil), "SrvUsersGroup.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "SrvUsersGroup.AddResponse")
	proto.RegisterType((*GetListRequest)(nil), "SrvUsersGroup.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "SrvUsersGroup.GetListResponse")
	proto.RegisterType((*GetRequest)(nil), "SrvUsersGroup.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "SrvUsersGroup.GetResponse")
	proto.RegisterType((*UpdateRequest)(nil), "SrvUsersGroup.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "SrvUsersGroup.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "SrvUsersGroup.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "SrvUsersGroup.DeleteResponse")
}

func init() {
	proto.RegisterFile("srv/srvusersgroup/proto/srvusersgroup.proto", fileDescriptor_2ef7a1dd69266781)
}

var fileDescriptor_2ef7a1dd69266781 = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0x05, 0x0a, 0xd4, 0xbd, 0x04, 0x34, 0x13, 0x1f, 0xc6, 0x66, 0x97, 0x90, 0x31, 0x31, 0xeb,
	0x1a, 0x21, 0x59, 0x9f, 0x25, 0xb2, 0x90, 0x34, 0x35, 0xb8, 0x9a, 0xb2, 0xfb, 0x6e, 0x75, 0x6e,
	0x56, 0x12, 0x96, 0xc1, 0x99, 0x29, 0xba, 0x7e, 0x9c, 0x1f, 0xe5, 0x17, 0x98, 0x4e, 0xa7, 0x2d,
	0x6d, 0x5d, 0x13, 0x7d, 0xeb, 0x39, 0x73, 0x38, 0xf7, 0xce, 0x39, 0xa5, 0xf0, 0x42, 0xc9, 0xfd,
	0x44, 0xc9, 0x7d, 0xac, 0x50, 0xaa, 0x1b, 0x29, 0xe2, 0xdd, 0x64, 0x27, 0x85, 0x16, 0x65, 0x6e,
	0x6c, 0x38, 0xd2, 0x5f, 0xc9, 0xfd, 0x75, 0x42, 0xfa, 0x09, 0xc9, 0x7e, 0x36, 0x01, 0x0a, 0x48,
	0x06, 0xd0, 0x0a, 0x16, 0xb4, 0x39, 0x6a, 0x9e, 0x3a, 0x61, 0x2b, 0x58, 0x10, 0x02, 0xed, 0xcb,
	0xe8, 0x16, 0x69, 0x6b, 0xd4, 0x3c, 0x3d, 0x0a, 0xcd, 0x33, 0xf1, 0xe0, 0xc1, 0x87, 0x48, 0xe2,
	0x56, 0x07, 0x0b, 0xea, 0x18, 0x65, 0x8e, 0xc9, 0x63, 0xe8, 0xac, 0x84, 0xd4, 0x8a, 0xb6, 0xcd,
	0x41, 0x0a, 0x8c, 0x8b, 0xd0, 0x48, 0x3b, 0xd6, 0x45, 0x68, 0x24, 0x43, 0x80, 0xb9, 0xc4, 0x48,
	0xe3, 0xd5, 0xfa, 0x16, 0x69, 0xd7, 0xc8, 0x0f, 0x18, 0xf2, 0x0c, 0x06, 0xcb, 0x48, 0xe9, 0xeb,
	0x1d, 0xcf, 0x34, 0xae, 0xd1, 0x54, 0x58, 0xf6, 0x1a, 0x60, 0xc6, 0x79, 0x88, 0x5f, 0x63, 0x54,
	0x9a, 0x4c, 0xa0, 0xf3, 0x4e, 0x70, 0xdc, 0x98, 0x2b, 0xf4, 0xce, 0x9f, 0x8c, 0x4b, 0xb7, 0x1d,
	0x17, 0x8f, 0x61, 0xaa, 0x63, 0x4f, 0xa1, 0x67, 0x7e, 0xae, 0x76, 0x62, 0xab, 0x30, 0xd9, 0xff,
	0x12, 0xbf, 0xe5, 0x11, 0xa4, 0x80, 0x49, 0x18, 0xf8, 0xa8, 0x97, 0x6b, 0xa5, 0xb3, 0x39, 0x26,
	0x83, 0x1b, 0x5c, 0xad, 0x7f, 0xa0, 0x95, 0xe6, 0x98, 0x9c, 0xc1, 0xa3, 0x79, 0x2c, 0x93, 0x40,
	0x12, 0x2a, 0xd8, 0x72, 0xfc, 0x6e, 0xf2, 0x73, 0xc2, 0x1a, 0x4f, 0x28, 0xb8, 0xef, 0x25, 0x47,
	0x79, 0x71, 0x67, 0xa2, 0x3c, 0x0a, 0x33, 0xc8, 0x3e, 0xc2, 0xc3, 0x7c, 0xa6, 0x5d, 0x6e, 0x08,
	0x70, 0x25, 0x74, 0xb4, 0x99, 0x8b, 0x78, 0xab, 0xed, 0xd8, 0x03, 0x86, 0xbc, 0x84, 0x76, 0xa2,
	0xa7, 0xad, 0x91, 0xf3, 0xf7, 0xbb, 0x1b, 0x19, 0x3b, 0x06, 0xf0, 0x31, 0xbf, 0x51, 0xa5, 0x79,
	0x36, 0x85, 0x9e, 0x39, 0xb5, 0xb3, 0xff, 0x39, 0xd8, 0x37, 0xd0, 0x4f, 0x5b, 0xfa, 0xef, 0x6a,
	0xce, 0x60, 0x90, 0x39, 0xd8, 0x25, 0x28, 0xb8, 0x29, 0xc3, 0xed, 0xa2, 0x19, 0x64, 0xcf, 0xa1,
	0xbf, 0xc0, 0x0d, 0x16, 0xd3, 0x28, 0xb8, 0x01, 0x9f, 0x49, 0x19, 0xdd, 0xd1, 0xe6, 0xc8, 0x49,
	0x82, 0xb5, 0x30, 0xb1, 0xcd, 0xa4, 0x85, 0x6d, 0xca, 0xe4, 0xb6, 0x16, 0x9e, 0xff, 0x6a, 0x41,
	0xf9, 0xff, 0x42, 0xa6, 0xe0, 0xcc, 0x38, 0x27, 0xd5, 0xed, 0x8b, 0x57, 0xd0, 0xf3, 0xfe, 0x74,
	0x94, 0x4e, 0x62, 0x0d, 0xf2, 0x16, 0x5c, 0x5b, 0x2b, 0x39, 0xa9, 0x08, 0xcb, 0xaf, 0x98, 0x37,
	0xbc, 0xef, 0x38, 0xf7, 0x9a, 0x82, 0xe3, 0xa3, 0xae, 0xed, 0x52, 0x94, 0x5a, 0xdb, 0xe5, 0xa0,
	0x51, 0xd6, 0x20, 0x3e, 0x74, 0xd3, 0xfc, 0xc8, 0x71, 0xb5, 0x8c, 0xc3, 0xe6, 0xbc, 0x93, 0x7b,
	0x4e, 0x73, 0xa3, 0x25, 0xf4, 0x2e, 0x22, 0xfd, 0xf9, 0x4b, 0x1a, 0x5b, 0xcd, 0xad, 0xd4, 0x4c,
	0xcd, 0xad, 0x5c, 0x06, 0x6b, 0x7c, 0xea, 0x9a, 0x0f, 0xd5, 0xab, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x65, 0x33, 0xfc, 0x83, 0xd7, 0x04, 0x00, 0x00,
}
