// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/srvcolumns/proto/srvcolumns.proto

// import public "google/protobuf/timestamp.proto";

package SrvColumns

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SrvColumns service

type SrvColumnsService interface {
	// 添回
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
	// 获取列表
	GetList(ctx context.Context, in *GetListRequest, opts ...client.CallOption) (*GetListResponse, error)
	// 获取单个信息
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	// 修改
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	// 批量删除
	BatchDelete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type srvColumnsService struct {
	c    client.Client
	name string
}

func NewSrvColumnsService(name string, c client.Client) SrvColumnsService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "SrvColumns"
	}
	return &srvColumnsService{
		c:    c,
		name: name,
	}
}

func (c *srvColumnsService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "SrvColumns.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvColumnsService) GetList(ctx context.Context, in *GetListRequest, opts ...client.CallOption) (*GetListResponse, error) {
	req := c.c.NewRequest(c.name, "SrvColumns.GetList", in)
	out := new(GetListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvColumnsService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "SrvColumns.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvColumnsService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "SrvColumns.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *srvColumnsService) BatchDelete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "SrvColumns.BatchDelete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SrvColumns service

type SrvColumnsHandler interface {
	// 添回
	Add(context.Context, *AddRequest, *AddResponse) error
	// 获取列表
	GetList(context.Context, *GetListRequest, *GetListResponse) error
	// 获取单个信息
	Get(context.Context, *GetRequest, *GetResponse) error
	// 修改
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	// 批量删除
	BatchDelete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterSrvColumnsHandler(s server.Server, hdlr SrvColumnsHandler, opts ...server.HandlerOption) error {
	type srvColumns interface {
		Add(ctx context.Context, in *AddRequest, out *AddResponse) error
		GetList(ctx context.Context, in *GetListRequest, out *GetListResponse) error
		Get(ctx context.Context, in *GetRequest, out *GetResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		BatchDelete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type SrvColumns struct {
		srvColumns
	}
	h := &srvColumnsHandler{hdlr}
	return s.Handle(s.NewHandler(&SrvColumns{h}, opts...))
}

type srvColumnsHandler struct {
	SrvColumnsHandler
}

func (h *srvColumnsHandler) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.SrvColumnsHandler.Add(ctx, in, out)
}

func (h *srvColumnsHandler) GetList(ctx context.Context, in *GetListRequest, out *GetListResponse) error {
	return h.SrvColumnsHandler.GetList(ctx, in, out)
}

func (h *srvColumnsHandler) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.SrvColumnsHandler.Get(ctx, in, out)
}

func (h *srvColumnsHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.SrvColumnsHandler.Update(ctx, in, out)
}

func (h *srvColumnsHandler) BatchDelete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.SrvColumnsHandler.BatchDelete(ctx, in, out)
}
