// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: srv/usersgroup/v1/proto/proto.proto

// import public "google/protobuf/timestamp.proto";

package ProtoUsersGroup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProtoUsersGroup service

type ProtoUsersGroupService interface {
	// 添回用户组
	Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error)
	// 获取用户组列表
	GetList(ctx context.Context, in *GetListRequest, opts ...client.CallOption) (*GetListResponse, error)
	// 获取单个用户组
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	// 修改用户组信息
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	// 批量删除用户组
	BatchDelete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
}

type protoUsersGroupService struct {
	c    client.Client
	name string
}

func NewProtoUsersGroupService(name string, c client.Client) ProtoUsersGroupService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "ProtoUsersGroup"
	}
	return &protoUsersGroupService{
		c:    c,
		name: name,
	}
}

func (c *protoUsersGroupService) Add(ctx context.Context, in *AddRequest, opts ...client.CallOption) (*AddResponse, error) {
	req := c.c.NewRequest(c.name, "ProtoUsersGroup.Add", in)
	out := new(AddResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoUsersGroupService) GetList(ctx context.Context, in *GetListRequest, opts ...client.CallOption) (*GetListResponse, error) {
	req := c.c.NewRequest(c.name, "ProtoUsersGroup.GetList", in)
	out := new(GetListResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoUsersGroupService) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.name, "ProtoUsersGroup.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoUsersGroupService) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.name, "ProtoUsersGroup.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *protoUsersGroupService) BatchDelete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.name, "ProtoUsersGroup.BatchDelete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProtoUsersGroup service

type ProtoUsersGroupHandler interface {
	// 添回用户组
	Add(context.Context, *AddRequest, *AddResponse) error
	// 获取用户组列表
	GetList(context.Context, *GetListRequest, *GetListResponse) error
	// 获取单个用户组
	Get(context.Context, *GetRequest, *GetResponse) error
	// 修改用户组信息
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	// 批量删除用户组
	BatchDelete(context.Context, *DeleteRequest, *DeleteResponse) error
}

func RegisterProtoUsersGroupHandler(s server.Server, hdlr ProtoUsersGroupHandler, opts ...server.HandlerOption) error {
	type protoUsersGroup interface {
		Add(ctx context.Context, in *AddRequest, out *AddResponse) error
		GetList(ctx context.Context, in *GetListRequest, out *GetListResponse) error
		Get(ctx context.Context, in *GetRequest, out *GetResponse) error
		Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error
		BatchDelete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error
	}
	type ProtoUsersGroup struct {
		protoUsersGroup
	}
	h := &protoUsersGroupHandler{hdlr}
	return s.Handle(s.NewHandler(&ProtoUsersGroup{h}, opts...))
}

type protoUsersGroupHandler struct {
	ProtoUsersGroupHandler
}

func (h *protoUsersGroupHandler) Add(ctx context.Context, in *AddRequest, out *AddResponse) error {
	return h.ProtoUsersGroupHandler.Add(ctx, in, out)
}

func (h *protoUsersGroupHandler) GetList(ctx context.Context, in *GetListRequest, out *GetListResponse) error {
	return h.ProtoUsersGroupHandler.GetList(ctx, in, out)
}

func (h *protoUsersGroupHandler) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.ProtoUsersGroupHandler.Get(ctx, in, out)
}

func (h *protoUsersGroupHandler) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.ProtoUsersGroupHandler.Update(ctx, in, out)
}

func (h *protoUsersGroupHandler) BatchDelete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.ProtoUsersGroupHandler.BatchDelete(ctx, in, out)
}
