// Code generated by protoc-gen-go. DO NOT EDIT.
// source: srv/users/v1/proto/proto.proto

// import public "google/protobuf/timestamp.proto";

package ProtoUsers

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	// 编号Id
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// 用户名称
	UserName string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	// 真实姓名或昵称
	RealyName string `protobuf:"bytes,3,opt,name=RealyName,proto3" json:"RealyName,omitempty"`
	// 密码
	Password string `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	// authkey
	AuthKey string `protobuf:"bytes,5,opt,name=AuthKey,proto3" json:"AuthKey,omitempty"`
	// Email
	Email string `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	// 是否删除
	IsDel bool `protobuf:"varint,7,opt,name=IsDel,proto3" json:"IsDel,omitempty"`
	// 备注
	Note                 string   `protobuf:"bytes,8,opt,name=Note,proto3" json:"Note,omitempty"`
	ParentID             int64    `protobuf:"varint,9,opt,name=ParentID,proto3" json:"ParentID,omitempty"`
	CreateTime           int64    `protobuf:"varint,10,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	LastUpdateTime       int64    `protobuf:"varint,11,opt,name=LastUpdateTime,proto3" json:"LastUpdateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *User) GetRealyName() string {
	if m != nil {
		return m.RealyName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetAuthKey() string {
	if m != nil {
		return m.AuthKey
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetIsDel() bool {
	if m != nil {
		return m.IsDel
	}
	return false
}

func (m *User) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *User) GetParentID() int64 {
	if m != nil {
		return m.ParentID
	}
	return 0
}

func (m *User) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *User) GetLastUpdateTime() int64 {
	if m != nil {
		return m.LastUpdateTime
	}
	return 0
}

type AddRequest struct {
	Model                *User    `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetModel() *User {
	if m != nil {
		return m.Model
	}
	return nil
}

type AddResponse struct {
	NewID                int64    `protobuf:"varint,1,opt,name=NewID,proto3" json:"NewID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetNewID() int64 {
	if m != nil {
		return m.NewID
	}
	return 0
}

type GetListRequest struct {
	PageSize             int64    `protobuf:"varint,1,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	CurrentPageIndex     int64    `protobuf:"varint,2,opt,name=CurrentPageIndex,proto3" json:"CurrentPageIndex,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListRequest) Reset()         { *m = GetListRequest{} }
func (m *GetListRequest) String() string { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()    {}
func (*GetListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{3}
}

func (m *GetListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListRequest.Unmarshal(m, b)
}
func (m *GetListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListRequest.Marshal(b, m, deterministic)
}
func (m *GetListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListRequest.Merge(m, src)
}
func (m *GetListRequest) XXX_Size() int {
	return xxx_messageInfo_GetListRequest.Size(m)
}
func (m *GetListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListRequest proto.InternalMessageInfo

func (m *GetListRequest) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetListRequest) GetCurrentPageIndex() int64 {
	if m != nil {
		return m.CurrentPageIndex
	}
	return 0
}

func (m *GetListRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

type GetListResponse struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
	List                 []*User  `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListResponse) Reset()         { *m = GetListResponse{} }
func (m *GetListResponse) String() string { return proto.CompactTextString(m) }
func (*GetListResponse) ProtoMessage()    {}
func (*GetListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{4}
}

func (m *GetListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListResponse.Unmarshal(m, b)
}
func (m *GetListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListResponse.Marshal(b, m, deterministic)
}
func (m *GetListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListResponse.Merge(m, src)
}
func (m *GetListResponse) XXX_Size() int {
	return xxx_messageInfo_GetListResponse.Size(m)
}
func (m *GetListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetListResponse proto.InternalMessageInfo

func (m *GetListResponse) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *GetListResponse) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

type GetRequest struct {
	ID                   int64    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{5}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

type GetResponse struct {
	Model                *User    `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{6}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetModel() *User {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateRequest struct {
	Model                *User    `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetModel() *User {
	if m != nil {
		return m.Model
	}
	return nil
}

type UpdateResponse struct {
	// 是否更新成功
	Updated              int64    `protobuf:"varint,1,opt,name=Updated,proto3" json:"Updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

type DeleteRequest struct {
	IDArray              []string `protobuf:"bytes,1,rep,name=IDArray,proto3" json:"IDArray,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetIDArray() []string {
	if m != nil {
		return m.IDArray
	}
	return nil
}

type DeleteResponse struct {
	// 是否删除成功,批量删除不需要返回值
	Deleted              int64    `protobuf:"varint,1,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a43aea674b38bed, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "ProtoUsers.User")
	proto.RegisterType((*AddRequest)(nil), "ProtoUsers.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "ProtoUsers.AddResponse")
	proto.RegisterType((*GetListRequest)(nil), "ProtoUsers.GetListRequest")
	proto.RegisterType((*GetListResponse)(nil), "ProtoUsers.GetListResponse")
	proto.RegisterType((*GetRequest)(nil), "ProtoUsers.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "ProtoUsers.GetResponse")
	proto.RegisterType((*UpdateRequest)(nil), "ProtoUsers.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "ProtoUsers.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "ProtoUsers.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "ProtoUsers.DeleteResponse")
}

func init() { proto.RegisterFile("srv/users/v1/proto/proto.proto", fileDescriptor_2a43aea674b38bed) }

var fileDescriptor_2a43aea674b38bed = []byte{
	// 546 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0x93, 0xfe, 0x9e, 0x6a, 0x65, 0xb2, 0x10, 0x98, 0x80, 0xaa, 0xca, 0xa0, 0xa9, 0xec,
	0xa2, 0x15, 0x03, 0x44, 0x6f, 0xbb, 0x06, 0xaa, 0x88, 0x51, 0xa6, 0xb0, 0x89, 0xeb, 0x40, 0x8e,
	0x58, 0xa5, 0xb4, 0x29, 0xb6, 0xb3, 0x51, 0x1e, 0x89, 0xb7, 0xe1, 0x8d, 0x90, 0xed, 0xfc, 0xb2,
	0x5e, 0x6c, 0x37, 0xae, 0xbf, 0xef, 0xfc, 0x7f, 0xc7, 0x0d, 0x0c, 0x04, 0xbf, 0x9e, 0x24, 0x02,
	0xb9, 0x98, 0x5c, 0xbf, 0x9a, 0x6c, 0x79, 0x2c, 0x63, 0x73, 0x8e, 0xf5, 0x49, 0xe0, 0x5c, 0xfd,
	0x5c, 0x2a, 0x07, 0xf6, 0xc7, 0x82, 0x86, 0xba, 0x91, 0x3e, 0x58, 0x9e, 0x4b, 0xeb, 0xc3, 0xfa,
	0xc8, 0xf6, 0x2d, 0xcf, 0x25, 0x0e, 0x74, 0x14, 0xbf, 0x0c, 0xd6, 0x48, 0xad, 0x61, 0x7d, 0xd4,
	0xf5, 0x73, 0x4c, 0x9e, 0x41, 0xd7, 0xc7, 0x20, 0xda, 0x69, 0xa3, 0xad, 0x8d, 0x05, 0xa1, 0x22,
	0xcf, 0x03, 0x21, 0x6e, 0x62, 0x1e, 0xd2, 0x86, 0x89, 0xcc, 0x30, 0xa1, 0xd0, 0x9e, 0x25, 0xf2,
	0xea, 0x23, 0xee, 0x68, 0x53, 0x9b, 0x32, 0x48, 0x1e, 0x42, 0xf3, 0xfd, 0x3a, 0x58, 0x45, 0xb4,
	0xa5, 0x79, 0x03, 0x14, 0xeb, 0x09, 0x17, 0x23, 0xda, 0x1e, 0xd6, 0x47, 0x1d, 0xdf, 0x00, 0x42,
	0xa0, 0xb1, 0x8c, 0x25, 0xd2, 0x8e, 0x76, 0xd5, 0x77, 0x53, 0x95, 0xe3, 0x46, 0x7a, 0x2e, 0xed,
	0xea, 0x29, 0x72, 0x4c, 0x06, 0x00, 0x73, 0x8e, 0x81, 0xc4, 0x8b, 0xd5, 0x1a, 0x29, 0x68, 0x6b,
	0x89, 0x21, 0x47, 0xd0, 0x3f, 0x0b, 0x84, 0xbc, 0xdc, 0x86, 0x99, 0x4f, 0x4f, 0xfb, 0xfc, 0xc7,
	0xb2, 0x37, 0x00, 0xb3, 0x30, 0xf4, 0xf1, 0x67, 0x82, 0x42, 0x92, 0x23, 0x68, 0x7e, 0x8a, 0x43,
	0x8c, 0xb4, 0x68, 0xbd, 0x93, 0xc3, 0x71, 0x21, 0xeb, 0x58, 0x9d, 0xbe, 0x31, 0xb3, 0xe7, 0xd0,
	0xd3, 0x51, 0x62, 0x1b, 0x6f, 0x04, 0xaa, 0x91, 0x96, 0x78, 0x93, 0x6b, 0x6d, 0x00, 0xe3, 0xd0,
	0x5f, 0xa0, 0x3c, 0x5b, 0x09, 0x99, 0xa5, 0xd7, 0x03, 0xfd, 0xc0, 0x2f, 0xab, 0xdf, 0x98, 0xba,
	0xe6, 0x98, 0x1c, 0xc3, 0xe1, 0x3c, 0xe1, 0x6a, 0x3a, 0x45, 0x79, 0x9b, 0x10, 0x7f, 0xe9, 0x25,
	0xd9, 0xfe, 0x2d, 0x5e, 0x49, 0xfe, 0x99, 0x87, 0xc8, 0x4f, 0x77, 0xe9, 0xaa, 0x32, 0xc8, 0xbe,
	0xc2, 0x83, 0xbc, 0x66, 0xda, 0xdc, 0x00, 0xe0, 0x22, 0x96, 0x41, 0x34, 0x8f, 0x93, 0x8d, 0x4c,
	0xcb, 0x96, 0x18, 0xf2, 0x02, 0x1a, 0xca, 0x9f, 0x5a, 0x43, 0x7b, 0xef, 0xc8, 0xda, 0xca, 0xa6,
	0x00, 0x0b, 0xcc, 0x07, 0xb9, 0xc7, 0xcb, 0x62, 0x6f, 0xa1, 0xa7, 0x23, 0xd3, 0x76, 0xee, 0x2a,
	0xf1, 0x3b, 0x38, 0x30, 0x6b, 0xba, 0xef, 0x6e, 0x8e, 0xa1, 0x9f, 0x05, 0xa6, 0x25, 0x29, 0xb4,
	0x0d, 0x13, 0xa6, 0x2d, 0x67, 0x90, 0xbd, 0x84, 0x03, 0x17, 0x23, 0x2c, 0x8a, 0x50, 0x68, 0x7b,
	0xee, 0x8c, 0xf3, 0x60, 0x47, 0xeb, 0x43, 0x5b, 0x29, 0x9b, 0x42, 0x95, 0x36, 0x73, 0x2d, 0xd2,
	0x1a, 0x26, 0x4f, 0x9b, 0xc2, 0x93, 0xbf, 0x16, 0x94, 0xfe, 0x90, 0x64, 0x0a, 0xf6, 0x2c, 0x0c,
	0xc9, 0xa3, 0x72, 0xc7, 0xc5, 0xa3, 0x73, 0x1e, 0xdf, 0xe2, 0x4d, 0x01, 0x56, 0x23, 0x2e, 0xb4,
	0xd3, 0x75, 0x12, 0xa7, 0xec, 0x55, 0x7d, 0x57, 0xce, 0xd3, 0xbd, 0xb6, 0x3c, 0xcb, 0x14, 0xec,
	0x05, 0xca, 0x6a, 0xfd, 0x62, 0x99, 0xd5, 0xfa, 0xa5, 0x55, 0xb1, 0x1a, 0x99, 0x41, 0xcb, 0x48,
	0x45, 0x9e, 0x54, 0xe4, 0x2e, 0x2f, 0xc6, 0x71, 0xf6, 0x99, 0xf2, 0x14, 0x1f, 0xa0, 0x77, 0x1a,
	0xc8, 0xef, 0x57, 0x46, 0x9b, 0x6a, 0x9e, 0x8a, 0xf6, 0xd5, 0x3c, 0x55, 0xad, 0x59, 0xed, 0x5b,
	0x4b, 0x7f, 0xe8, 0x5e, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x5b, 0x1a, 0xa4, 0x0a, 0x05,
	0x00, 0x00,
}
